[package]
name = "task-local-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.21", default-features = false }
syn = { version = "1.0.101", default-features = false, features = ["derive", "parsing", "proc-macro"] }
